line-length = 100
target-version = "py310"

[lint]
select = [
    "E9",
    "F63",
    "F7",
    "F82",
]
ignore = [
    "F821",
    "F822",
    "E501",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
